name: Pipeline CD & DAST

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cd-production
  cancel-in-progress: false

jobs:

  deploy-staging:
    name: 0. Deploy to Staging
    runs-on: ubuntu-latest

    environment:
      name: staging

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start staging application
        run: |
          npm run start &
          sleep 10

      - name: Validate staging
        run: |
          curl --fail http://127.0.0.1:3000 || exit 1


  dast-scan:
    name: 1. DAST - OWASP ZAP
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Start staging application
        run: |
          npm ci
          npm run build
          npm run start &
          sleep 10

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: "http://127.0.0.1:3000"
          cmd_options: "-a"


  deploy-production:
    name: 2. Deploy to Production
    runs-on: ubuntu-latest
    needs: dast-scan

    environment:
      name: production

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Production Deployment
        run: |
          echo "DAST aprovado!"
          echo "Executando deploy em Produção..."

      - name: Enable Monitoring
        run: |
          echo "Ativando monitoramento com Prometheus/Grafana..."