name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - feature/*

permissions:
  contents: read

jobs:

  test:
    name: Build, Lint and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js 
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm
      
      - name: Install dependencies
        run: npm ci 
      
      - name: TypeScript Check
        run: npm run typecheck

      - name: Lint
        run: npm run lint'
      
      - name: Run tests 
        run: npm run test:ci

      - name: Build
        run: npm run build