name: Security Pipeline

on:
  pull_request:
  push:
    branches:
      - main
      - chore/*
      - feature/*
  workflow_dispatch:

permissions:
  contents: read

jobs:

  gitleaks:
    name: Secret Scan - Gitleaks
    runs-onm: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    needs: gitleaks

    permissions:
      contents: read

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript

  npm-audit:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    needs: gitleaks

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Setup Node.Js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm ci typescript@6 -D

      - name: Audit dependencies
        run: npm audit --audit-level=high
        
  docker: 
    name: Container Security - Trivy
    runs-on: ubuntu-latest
    needs: 
      - test

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      
      - name: Build image
        run: |
          docker build \
          - t patient-api:${{ github.sha }} \
          .

  trivy:
    name: Container Security - Trivy
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: |
          docker build \
            -t patient-api:${{ github.sha }} \
            .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: patient-api:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

  checkov:
    name: IaC Security - Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          quiet: true
          soft_fail: false